### ISSUE TITLE
Console spam when spawning screens

### ISSUE THREAD

**Issue by wrefgtzweve** [stepa2/improved-rt-cameras#1]
Console gets spammed when players spawn rt screens.
![image](https://user-images.githubusercontent.com/69946827/149966509-b90af604-64cf-46a6-b853-91d08e813b4a.png)

The camera works fine when linked up however:
![image](https://user-images.githubusercontent.com/69946827/149966783-3e9687f5-1906-4449-a49c-4b3b704b55bf.png)

Would it be possible to hide the console print or limit it in some way? if any player spawns a single screen this amount of text shows up
![image](https://user-images.githubusercontent.com/69946827/149966927-09d140f2-94d9-439a-a15b-ebbd694608f9.png)

**Comment by stepa2** [comment]
This addon is now integrated into WireMod (however it seems not to work in multiplayer, and I have not fixed it yet).
This repository is mostly keeped for archival purposes
